name: morphosis_template
description: template for future flutter projects
version: 1.0.0+40

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  crypto: ^3.0.2
  curl_logger_dio_interceptor: ^0.0.3
  dartz: ^0.10.1
  device_info: ^2.0.3
  device_info_plus: ^4.0.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  equatable: ^2.0.3
  file: ^6.1.2
  file_picker: ^5.0.1
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_dynamic_links: ^4.3.3
  firebase_messaging: ^12.0.1
  firebase_performance: ^0.8.2+1
  firebase_remote_config: ^2.0.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_image_compress: ^1.1.1
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_offline: ^2.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  location: ^4.4.0
  logger: ^1.1.0
  md5_file_checksum: ^1.0.3
  mockito: ^5.3.0
  overlay_support: ^2.0.1
  package_info_plus: ^1.4.3
  path: ^1.8.1
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  scroll_when_needed: ^2.0.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  timeago: ^3.2.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  webview_flutter: ^3.0.4
  wifi_info_flutter: ^2.0.2

dev_dependencies:
  auto_route_generator: ^4.2.1
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  hive_generator: ^1.1.3
  http_mock_adapter: ^0.3.3
  import_path_converter: ^1.0.1
  import_sorter: ^4.6.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1
  model_generator: ^5.8.1
  retrofit_generator: ^4.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/translations/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icons/Logo Animation@3x.png
