// Mocks generated by Mockito 5.3.0 from annotations
// in morphosis_template/test/core/global/utils/notifications/local_notifications_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i5;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:morphosis_template/core/global/util/notifications/local_notifications.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlutterLocalNotificationsPlugin_0 extends _i1.SmartFake
    implements _i2.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_0(
      Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [LocalNotfications].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotfications extends _i1.Mock implements _i3.LocalNotfications {
  MockLocalNotfications() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(Invocation.getter(#flutterLocalNotificationsPlugin),
              returnValue: _FakeFlutterLocalNotificationsPlugin_0(
                  this, Invocation.getter(#flutterLocalNotificationsPlugin)))
          as _i2.FlutterLocalNotificationsPlugin);
  @override
  set flutterLocalNotificationsPlugin(
          _i2.FlutterLocalNotificationsPlugin?
              _flutterLocalNotificationsPlugin) =>
      super.noSuchMethod(
          Invocation.setter(#flutterLocalNotificationsPlugin,
              _flutterLocalNotificationsPlugin),
          returnValueForMissingStub: null);
  @override
  _i4.Future<void> initialize(
          {bool? requestAlertPermission = false,
          bool? requestBadgePermission = false,
          bool? requestSoundPermission = false}) =>
      (super.noSuchMethod(
              Invocation.method(#initialize, [], {
                #requestAlertPermission: requestAlertPermission,
                #requestBadgePermission: requestBadgePermission,
                #requestSoundPermission: requestSoundPermission
              }),
              returnValue: _i4.Future<void>.value(),
              returnValueForMissingStub: _i4.Future<void>.value())
          as _i4.Future<void>);
  @override
  _i4.Future<dynamic> selectNotification(
          String? payload, _i5.BuildContext? context) =>
      (super.noSuchMethod(
          Invocation.method(#selectNotification, [payload, context]),
          returnValue: _i4.Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<void> showNotification(
          {String? id, String? title, String? body}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #showNotification, [], {#id: id, #title: title, #body: body}),
              returnValue: _i4.Future<void>.value(),
              returnValueForMissingStub: _i4.Future<void>.value())
          as _i4.Future<void>);
}
