// Mocks generated by Mockito 5.3.0 from annotations
// in morphosis_template/test/features/todo/data/todo_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:morphosis_template/features/todo/data/todo_repo_impl.dart'
    as _i2;
import 'package:morphosis_template/features/todo/domain/entities/todo.dart'
    as _i3;
import 'package:morphosis_template/features/todo/services/todo_webservice.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Todo> getTodos() =>
      (super.noSuchMethod(Invocation.method(#getTodos, []),
          returnValue: <_i3.Todo>[]) as List<_i3.Todo>);
  @override
  _i4.Future<List<_i3.Todo>> fetchTodos() =>
      (super.noSuchMethod(Invocation.method(#fetchTodos, []),
              returnValue: _i4.Future<List<_i3.Todo>>.value(<_i3.Todo>[]))
          as _i4.Future<List<_i3.Todo>>);
  @override
  _i4.Future<void> saveTodo(String? todo) => (super.noSuchMethod(
      Invocation.method(#saveTodo, [todo]),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> updateTodo({int? id, bool? value}) => (super.noSuchMethod(
      Invocation.method(#updateTodo, [], {#id: id, #value: value}),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [TodoWebService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoWebService extends _i1.Mock implements _i5.TodoWebService {
  MockTodoWebService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i3.Todo>> getTodos() =>
      (super.noSuchMethod(Invocation.method(#getTodos, []),
              returnValue: _i4.Future<List<_i3.Todo>>.value(<_i3.Todo>[]))
          as _i4.Future<List<_i3.Todo>>);
}
